### ISSUE TITLE
Problem installing this layer

### ISSUE THREAD

**Issue by hilmandayo** [kenjimyzk/spacemacs-japanese#1]
Hello.
I've tried to install this layer by adding `japanese` to the `dotspacemacs-configuration-layers`, but I got this warning:

```
  Warnings:
      - Unknown layer japanese declared in dotfile.      
```

Why is this?

**Comment by hackn-in-github** [comment]
I think that you can use it if you create "japanese" directory in "~ /.emacs.d/private" and place "packages.el" there.
